# -*- coding: utf-8 -*-
"""WiDS_Week1_Day4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cEqjncQtARZEKpGLCkaFGmfqrbdysck_
"""

from bisect import bisect_left
from collections import deque
import random
import matplotlib.pyplot as plt

class Order:
  def __init__(self, agent_id, side, price, qty, timestamp):
    self.agent_id = agent_id
    self.side = side
    self.price = price
    self.qty = qty
    self.ts = timestamp

class Trade:
  def __init__(self, price, qty, buy_agent, sell_agent, timestamp):
    self.price = price
    self.qty = qty
    self.buy_agent = buy_agent
    self.sell_agent = sell_agent
    self.ts = timestamp

class OrderBook:
  def __init__(self):
    self.bids = {}
    self.asks = {}
    self.bid_prices = []
    self.ask_prices = []
    self.trades = []

  def best_bid(self):
    return -self.bid_prices[0] if self.bid_prices else None

  def best_ask(self):
    return self.ask_prices[0] if self.ask_prices else None

  def add_limit(self, order):
    if order.side == "buy":
      key = -order.price
      if order.price not in self.bids:
        idx = bisect_left(self.bid_prices, key)
        self.bid_prices.insert(idx, key)
        self.bids[order.price] = deque()
      self.bids[order.price].append(order)
    else:
      key = order.price
      if order.price not in self.asks:
        idx = bisect_left(self.ask_prices, key)
        self.ask_prices.insert(idx, key)
        self.asks[order.price] = deque()
      self.asks[order.price].append(order)

    self.match()

  def match(self):
    while self.bid_prices and self.ask_prices:
      bid_price = -self.bid_prices[0]
      ask_price = self.ask_prices[0]

      if bid_price < ask_price:
        break

      buy_order = self.bids[bid_price][0]
      sell_order = self.asks[ask_price][0]

      trade_qty = min(buy_order.qty, sell_order.qty)

      buy_order.qty -= trade_qty
      sell_order.qty -= trade_qty

      self.trades.append(
          Trade(
              price = ask_price,
              qty = trade_qty,
              buy_agent = buy_order.agent_id,
              sell_agent = sell_order.agent_id,
              timestamp = buy_order.ts
          )
      )

      if buy_order.qty == 0:
        self.bids[bid_price].popleft()
        if not self.bids[bid_price]:
          del self.bids[bid_price]
          self.bid_prices.pop(0)

      if sell_order.qty == 0:
        self.asks[ask_price].popleft()
        if not self.asks[ask_price]:
          del self.asks[ask_price]
          self.ask_prices.pop(0)

class MarketEnvironment:
  def __init__(self, agents):
    self.book = OrderBook()
    self.agents = agents
    self.time = 0
    self.spread_history = []

  def reset(self):
    self.time = 0
    self.book = OrderBook()
    self.spread_history = []

  def step(self):
    self.time += 1

    for agent in self.agents:
      order = agent.act(self)
      if order:
        self.book.add_limit(order)

    if self.book.best_bid() and self.book.best_ask():
      spread = self.book.best_ask() - self.book.best_bid()
      self.spread_history.append(spread)

class Agent:
  def __init__(self, agent_id):
    self.id = agent_id

  def act(self, env):
    raise NotImplementedError

class RandomTrader(Agent):
  def act(self, env):
    if random.random() > 0.3:
      return None

    side = random.choice(["buy", "sell"])
    price = 100 + random.randint(-5, 5)
    qty = random.randint(1, 5)

    return Order(
        agent_id = self.id,
        side = side,
        price = price,
        qty = qty,
        timestamp = env.time
    )

class MarketMaker(Agent):
  def act(self, env):
    mid = 100
    spread = 2

    side = random.choice(["buy", "sell"])
    price = mid - spread//2 if side == "buy" else mid + spread//2

    return Order(
        agent_id = self.id,
        side = side,
        price = price,
        qty = 3,
        timestamp = env.time
    )

agents = [
    MarketMaker(agent_id = 0),
    RandomTrader(agent_id = 1),
    RandomTrader(agent_id = 2),
    RandomTrader(agent_id = 3)
]

env = MarketEnvironment(agents)
env.reset()

for _ in range(500):
  env.step()

plt.plot(env.spread_history)
plt.title("Bid-Ask Spread Over Time")
plt.xlabel("Time Step")
plt.ylabel("Spread")
plt.show()