# -*- coding: utf-8 -*-
"""WiDS_Week1_Day3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C5-GAej_rSNu6d1c98j1c2Xf9LANcoF_
"""

import numpy as np
from bisect import bisect_left
from collections import deque
import matplotlib.pyplot as plt

class Order:
  def __init__(self, side, price, qty):
    self.side = side
    self.price = price
    self.qty = qty

class OrderBook:
  def __init__(self):
    self.bids = {}
    self.asks = {}
    self.bid_prices = []
    self.ask_prices = []

  def best_bid(self):
    return -self.bid_prices[0] if self.bid_prices else None

  def best_ask(self):
    return self.ask_prices[0] if self.ask_prices else None

  def add_limit(self, order):
    if order.side == "buy":
      key = -order.price
      if order.price not in self.bids:
        idx = bisect_left(self.bid_prices, key)
        self.bid_prices.insert(idx, key)
        self.bids[order.price] = deque()
      self.bids[order.price].append(order)

    else:
      key = order.price
      if order.price not in self.asks:
        idx = bisect_left(self.ask_prices, key)
        self.ask_prices.insert(idx, key)
        self.asks[order.price] = deque()
      self.asks[order.price].append(order)

    self.match()

  def add_market(self, side, qty):
    if side == "buy":
      while qty > 0 and self.ask_prices:
        price = self.ask_prices[0]
        order = self.asks[price][0]
        trade = min(qty, order.qty)
        qty -= trade
        order.qty -= trade

        if order.qty == 0:
          self.asks[price].popleft()
          if not self.asks[price]:
            del self.asks[price]
            self.ask_prices.pop(0)

    else:
      while qty > 0 and self.bid_prices:
        price = -self.bid_prices[0]
        order = self.bids[price][0]
        trade = min(qty, order.qty)
        qty -= trade
        order.qty -= trade

        if order.qty == 0:
          self.bids[price].popleft()
          if not self.bids[price]:
            del self.bids[price]
            self.bid_prices.pop(0)

  def match(self):
    while self.bid_prices and self.ask_prices:
      bid = -self.bid_prices[0]
      ask = self.ask_prices[0]
      if bid < ask:
        break

      bid_order = self.bids[bid][0]
      ask_order = self.asks[ask][0]

      trade = min(bid_order.qty, ask_order.qty)
      bid_order.qty -= trade
      ask_order.qty -= trade

      if bid_order.qty == 0:
        self.bids[bid].popleft()
        if not self.bids[bid]:
          del self.bids[bid]
          self.bid_prices.pop(0)

      if ask_order.qty == 0:
        self.asks[ask].popleft()
        if not self.asks[ask]:
          del self.asks[ask]
          self.ask_prices.pop(0)

book = OrderBook()
mid_price = 100
spreads = []

for _ in range(1000):
  side = np.random.choice(["buy", "sell"])
  qty = np.random.randint(1, 10)

  if np.random.rand() < 0.3:
    book.add_market(side, qty)
  else:
    price_offset = np.random.randint(1, 5)
    price = mid_price - price_offset if side == "buy" else mid_price + price_offset
    book.add_limit(Order(side, price, qty))

  if book.best_bid() and book.best_ask():
    spreads.append(book.best_ask() - book.best_bid())

plt.plot(spreads)
plt.title("Bid-Ask Spread Over Time")
plt.xlabel("Trade Index")
plt.ylabel("Spread")
plt.show()

bid_prices = sorted(book.bids.keys(), reverse=True)
ask_prices = sorted(book.asks.keys())

bid_qty = [sum(o.qty for o in book.bids[p]) for p in bid_prices]
ask_qty = [sum(o.qty for o in book.asks[p]) for p in ask_prices]

plt.barh(bid_prices, bid_qty)
plt.barh(ask_prices, ask_qty)
plt.title("Order Book Depth Snapshot")
plt.xlabel("Quantity")
plt.ylabel("Price")
plt.show()