# -*- coding: utf-8 -*-
"""WiDS_Week1_Day2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZ4O9dhxceycN53E2ZrLg6O_J0efXq3c
"""

from bisect import bisect_left
from collections import deque

class Order:
  def __init__(self, order_id, side, price, qty, timestamp):
    self.id = order_id
    self.side = side
    self.price = price
    self.qty = qty
    self.ts = timestamp

class OrderBook:
  def __init__(self):
    self.bids = {}
    self.asks = {}
    self.bid_prices =[]
    self.ask_prices =[]

  def add_limit(self, order):
    if order.side == 'buy':
      book = self.bids
      prices = self.bid_prices
      key = -order.price

      if order.price not in book:
        idx = bisect_left(prices, key)
        prices.insert(idx, key)
        book[order.price] = deque()

      book[order.price].append(order)

    else:
      book = self.asks
      prices = self.ask_prices
      key = order.price

      if order.price not in book:
        idx = bisect_left(prices, key)
        prices.insert(idx, key)
        book[order.price] = deque()

      book[order.price].append(order)

    self.match()

  def match(self):
    while self.bid_prices and self.ask_prices:
      best_bid_key = self.bid_prices[0]
      best_ask_price = self.ask_prices[0]

      best_bid_price = -best_bid_key

      if best_bid_price < best_ask_price:
        break

      bid_order = self.bids[best_bid_price][0]
      ask_order = self.asks[best_ask_price][0]

      trade_qty = min(bid_order.qty, ask_order.qty)

      bid_order.qty -= trade_qty
      ask_order.qty -= trade_qty

      print(f"TRADE {trade_qty} @ {best_ask_price}")

      if bid_order.qty == 0:
        self.bids[best_bid_price].popleft()
        if not self.bids[best_bid_price]:
          del self.bids[best_bid_price]
          self.bid_prices.pop(0)

      if ask_order.qty == 0:
        self.asks[best_ask_price].popleft()
        if not self.asks[best_ask_price]:
          del self.asks[best_ask_price]
          self.ask_prices.pop(0)

  def print_top5(self):
    print("BIDS: ")
    for k in self.bid_prices[:5]:
      price = -k
      qty = sum(o.qty for o in self.bids[price])
      print(price, qty)

    print("ASKS: ")
    for price in self.ask_prices[:5]:
      qty = sum(o.qty for o in self.asks[price])
      print(price, qty)


orders = [
    ('buy', 100, 10),
    ('buy', 101, 5),
    ('sell', 102, 7),
    ('sell', 101, 4)
]

def run():
  book = OrderBook()
  t = 0
  for side, price, qty in orders:
    t += 1
    book.add_limit(Order(t, side, price, qty, t))
  return book

book1 = run()
book2 = run()

book1.print_top5()
book2.print_top5()