# -*- coding: utf-8 -*-
"""WiDS_Week1_Day5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XlWlDeTzV77v0rfQrzBC1An3G3_gglwH
"""

import random
from bisect import bisect_left
from collections import deque
import matplotlib.pyplot as plt

SEED = 42
random.seed(SEED)

class Order:
  def __init__(self, order_id, agent_id, side, price, qty, timestamp):
    self.id = order_id
    self.agent_id = agent_id
    self.side = side
    self.price = price
    self.qty = qty
    self.ts = timestamp

class Trade:
  def __init__(self, price, qty, buy_agent, sell_agent, timestamp):
    self.price = price
    self.qty = qty
    self.buy_agent = buy_agent
    self.sell_agent = sell_agent
    self.ts = timestamp

class Logger:
  def __init__(self):
    self.orders = []
    self.trades = []

  def log_order(self, order):
    self.orders.append(order)

  def log_trade(self, trade):
    self.trades.append(trade)

class OrderBook:
  def __init__(self, logger):
    self.bids = {}
    self.asks = {}
    self.bid_prices = []
    self.ask_prices = []
    self.logger = logger

  def best_bid(self):
    return -self.bid_prices[0] if self.bid_prices else None

  def best_ask(self):
    return self.ask_prices[0] if self.ask_prices else None

  def add_limit(self, order):
    self.logger.log_order(order)

    if order.side == "buy":
      key = -order.price
      if order.price not in self.bids:
        idx = bisect_left(self.bid_prices, key)
        self.bid_prices.insert(idx, key)
        self.bids[order.price] = deque()
      self.bids[order.price].append(order)
    else:
      key = order.price
      if order.price not in self.asks:
        idx = bisect_left(self.ask_prices, key)
        self.ask_prices.insert(idx, key)
        self.asks[order.price] = deque()
      self.asks[order.price].append(order)

    self.match()

  def match(self):
    while self.bid_prices and self.ask_prices:
      bid_price = -self.bid_prices[0]
      ask_price = self.ask_prices[0]

      if bid_price < ask_price:
        break

      buy = self.bids[bid_price][0]
      sell = self.asks[ask_price][0]

      qty = min(buy.qty, sell.qty)

      buy.qty -= qty
      sell.qty -= qty

      trade = Trade(
          price = ask_price,
          qty = qty,
          buy_agent = buy.agent_id,
          sell_agent = sell.agent_id,
          timestamp = buy.ts
      )
      self.logger.log_trade(trade)

      if buy.qty == 0:
        self.bids[bid_price].popleft()
        if not self.bids[bid_price]:
          del self.bids[bid_price]
          self.bid_prices.pop(0)

      if sell.qty == 0:
        self.asks[ask_price].popleft()
        if not self.asks[ask_price]:
          del self.asks[ask_price]
          self.ask_prices.pop(0)

class MarketEnvironment:
  def __init__(self, agents):
    self.time = 0
    self.order_id = 0
    self.logger = Logger()
    self.book = OrderBook(self.logger)
    self.agents = agents
    self.spread_history = []

  def validate_order(self, order):
    if order.qty <= 0:
      return False
    if order.side not in ("buy", "sell"):
      return False
    return True

  def reset(self):
    self.time = 0
    self.order_id = 0
    self.logger = Logger()
    self.book = OrderBook(self.logger)
    self.spread_history = []

  def step(self):
    self.time += 1

    for agent in self.agents:
      intent = agent.act(self)
      if intent:
        self.order_id += 1
        order = Order(
            order_id = self.order_id,
            agent_id = agent.id,
            side = intent["side"],
            price = intent["price"],
            qty = intent["qty"],
            timestamp = self.time
        )

        if self.validate_order(order):
          self.book.add_limit(order)

    if self.book.best_bid() and self.book.best_ask():
      spread = self.book.best_ask() - self.book.best_bid()
      self.spread_history.append(spread)

class Agent:
  def __init__(self, agent_id):
    self.id = agent_id

  def act(self, env):
    raise NotImplementedError

class RandomTrader(Agent):
  def act(self, env):
    if random.random() > 0.3:
      return None

    return {
        "side": random.choice(["buy", "sell"]),
        "price": 100 + random.randint(-5, 5),
        "qty": random.randint(1, 5)
    }

class MarketMaker(Agent):
  def act(self, env):
    mid = 100
    spread = 2
    side = random.choice(["buy", "sell"])

    price = mid - spread//2 if side == "buy" else mid + spread//2

    return {
        "side": side,
        "price": price,
        "qty": 3
    }

agents = [
    MarketMaker(0),
    RandomTrader(1),
    RandomTrader(2),
    RandomTrader(3)
]

env = MarketEnvironment(agents)
env.reset()

for _ in range(500):
  env.step()

print("Total orders: ", len(env.logger.orders))
print("Total trades: ", len(env.logger.trades))

print("First 5 trades: ")
for t in env.logger.trades[:5]:
  print(vars(t))

plt.plot(env.spread_history)
plt.title("Bid-Ask Spread")
plt.xlabel("Time")
plt.ylabel("Spread")
plt.show()